// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// CreateTeam inserts a new team (the multi-tenant root) and returns the row.
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	// GetTeam returns the team with the given id, or sql.ErrNoRows if absent.
	GetTeam(ctx context.Context, id string) (Team, error)
}

var _ Querier = (*Queries)(nil)
