// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name)
VALUES (?, ?)
RETURNING id, name, created_at, updated_at
`

type CreateTeamParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// CreateTeam inserts a new team (the multi-tenant root) and returns the row.
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, created_at, updated_at FROM teams
WHERE id = ?
`

// GetTeam returns the team with the given id, or sql.ErrNoRows if absent.
func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
